#
# Configurations for GitHub's dependabot.
#
# Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#

version: 2
updates:

  # Check for updates to GitHub Actions every Tuesday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    # Allow up to 5 open pull requests at a time
    open-pull-requests-limit: 5
