trigger:
  branches:
    include:
    - master
    - 5.x

jobs:
- job:
  displayName: Build documentations

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    fetchDepth: 5

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda config --set always_yes yes --set changeps1 no
      conda config --prepend channels conda-forge
      conda config --set show_channel_urls True
    displayName: Config conda

  - bash: pip install -r requirements.txt
    displayName: Install Python dependencies

  - bash: |
      conda install -c conda-forge/label/dev gmt=6.0.0rc1
      gmt --version
    displayName: Install GMT

  - bash: curl -sSL https://raw.githubusercontent.com/seisman/install/master/install-SourceCodePro.sh | bash
    displayName: Install fonts

  # TinyTeX https://github.com/yihui/tinytex
  - bash: |
      echo ${HOME}/.TinyTeX/bin/x86_64-linux
      ls ${HOME}/.TinyTeX/bin/x86_64-linux
      echo "##vso[task.prependpath]$HOME/.TinyTeX/bin/x86_64-linux"
      wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
      tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth \
                    float wrapfig parskip capt-of needspace xcolor enumitem xindy fandol
    displayName: Install tinytex

  - bash: make build
    displayName: Build documentation

