trigger:
  branches:
    include:
    - master
    - 5.x

jobs:
- job:
  displayName: Build documentations

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    fetchDepth: 5

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda config --set always_yes yes --set changeps1 no
      conda config --prepend channels conda-forge
      conda config --set show_channel_urls True
    displayName: Config conda

  - bash: pip install -r requirements.txt
    displayName: Install dependencies

  - bash: conda install -c conda-forge/label/dev gmt=6.0.0rc1
    displayName: Install GMT
